# NumPy
Reference: Python Data Science Handbook by Jake VanderPlas
 https://jakevdp.github.io/PythonDataScienceHandbook

In [2]:
import numpy as np

In [2]:
np.__version__

'1.14.6'

In [3]:
np.abs?

In [4]:
# create arrays from lists
myNPArray = np.array([1,2,3])
myNPArray

array([1, 2, 3])

In [5]:
print(myNPArray)

[1 2 3]


In [3]:
myNPArray = np.array([1,2,3,"a"])
myNPArray

array(['1', '2', '3', 'a'], dtype='<U21')

In [5]:
type(myNPArray[0])

numpy.str_

In [9]:
myNPArray = np.array([1,2,3,3.2])
myNPArray

array([1. , 2. , 3. , 3.2])

In [7]:
myNPArray = np.array([1,2,3,False], dtype="float64")
myNPArray

array([1., 2., 3., 0.])

In [9]:
# 2-dimensional
myNPArray = np.array([range(i,i+5) for i in range(10,21,2)])
myNPArray

array([[10, 11, 12, 13, 14],
       [12, 13, 14, 15, 16],
       [14, 15, 16, 17, 18],
       [16, 17, 18, 19, 20],
       [18, 19, 20, 21, 22],
       [20, 21, 22, 23, 24]])

In [10]:
myA =np.zeros(10, dtype=bool)
myA

array([False, False, False, False, False, False, False, False, False,
       False])

In [19]:
np.zeros((10,10), dtype=int)

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [15]:
myA = np.zeros((2,3), dtype=int)
myA

array([[0, 0, 0],
       [0, 0, 0]])

In [20]:
myA = np.ones((2,3), dtype=bool)
myA

array([[ True,  True,  True],
       [ True,  True,  True]])

In [22]:
myA = np.ones?

In [17]:
myA = np.full((5,5), np.BUFSIZE)
myA

array([[8192, 8192, 8192, 8192, 8192],
       [8192, 8192, 8192, 8192, 8192],
       [8192, 8192, 8192, 8192, 8192],
       [8192, 8192, 8192, 8192, 8192],
       [8192, 8192, 8192, 8192, 8192]])

In [26]:
np.arange(10,5,-1)

array([10,  9,  8,  7,  6])

In [27]:
np.arange(5,10)

array([5, 6, 7, 8, 9])

In [28]:
np.arange(0,106,5)

array([  0,   5,  10,  15,  20,  25,  30,  35,  40,  45,  50,  55,  60,
        65,  70,  75,  80,  85,  90,  95, 100, 105])

In [19]:
# 20 evenly spaced numbers from 1 to 10
np.linspace(1,10,20)

array([ 1.        ,  1.47368421,  1.94736842,  2.42105263,  2.89473684,
        3.36842105,  3.84210526,  4.31578947,  4.78947368,  5.26315789,
        5.73684211,  6.21052632,  6.68421053,  7.15789474,  7.63157895,
        8.10526316,  8.57894737,  9.05263158,  9.52631579, 10.        ])

In [19]:
# 5x5 array of uniformly distributed random values
np.random.random((5,5))

array([[0.7750819 , 0.40652017, 0.59238717, 0.57089007, 0.20344798],
       [0.96451419, 0.96808081, 0.27636465, 0.45197746, 0.69132263],
       [0.78550416, 0.33034969, 0.57095712, 0.93448033, 0.19699576],
       [0.12972503, 0.65187621, 0.0410735 , 0.21266972, 0.71547536],
       [0.37407228, 0.01762699, 0.02799374, 0.74171321, 0.33186384]])

In [30]:
np.random.random(5)

array([0.8978157 , 0.32754791, 0.50199968, 0.75116394, 0.19070928])

In [21]:
# 5x5 array of normally distributed random values with mean 0 and std dev 1
np.random.normal(0,1, (5,5))

array([[-0.50397107,  2.28684449,  0.56491543,  2.88091272, -0.70044892],
       [ 0.6384216 ,  0.23816643,  1.47982521,  1.00940176,  0.13857612],
       [ 0.26032414, -0.0269408 ,  2.19393083,  0.61046646, -0.31158598],
       [-0.90222235, -0.83478033, -0.46773275,  1.27316838,  0.06989605],
       [-0.01962598, -2.00072806, -1.32593327, -0.80415608, -0.664522  ]])

In [20]:
np.random.normal?

In [22]:
# 10x10 identity matrix
np.eye(10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [31]:
#5x5 empty matrix, values are what happens to be in that memory location
np.empty((5,5))

array([[0.00000000e+000, 0.00000000e+000, 6.95242731e-310,
        6.95242315e-310, 6.95242315e-310],
       [6.95242460e-310, 6.95242710e-310, 6.95242460e-310,
        6.95242317e-310, 6.95242483e-310],
       [6.95242463e-310, 6.95242318e-310, 6.95242315e-310,
        6.95242315e-310, 6.95242315e-310],
       [6.95242315e-310, 6.95242481e-310, 6.95242480e-310,
        6.95242461e-310, 6.95242318e-310],
       [6.95242461e-310, 6.95242491e-310, 6.95242493e-310,
        6.95242767e-310, 6.95242316e-310]])

In [24]:
myA.ndim

2

In [25]:
myA.shape

(5, 5)

In [26]:
myA.size

25

In [27]:
myA.dtype

dtype('float64')

In [27]:
myA.itemsize

8

In [29]:
myA.nbytes

48

In [28]:
myA[0,0]

8192

In [29]:
myB = np.random.normal(0,1, (5,5))
print(myB)
myB[0,-1]

[[ 0.34327789  0.74329595 -0.0220292  -0.79873751  0.13652587]
 [-1.05596487 -1.08655701  0.8013661   0.64413154 -0.33560226]
 [-0.25714345 -0.59916892  0.2941537   0.95005002 -0.75550508]
 [ 0.95224279  0.34673325 -0.13921861 -0.33049603  1.42037641]
 [-0.71289796  1.12905663  0.50378533  0.68942498 -0.5605445 ]]


0.13652587411380748

In [30]:
myB[0,0]

0.343277889977529