In [1]:
import numpy as np

ridership = np.array([
[ 0, 0, 2, 5, 0],
[1478, 3877, 3674, 2328, 2539],
[1613, 4088, 3991, 6461, 2691],
[1560, 3392, 3826, 4787, 2613],
[1608, 4802, 3932, 4477, 2705],
[1576, 3933, 3909, 4979, 2685],
[ 95, 229, 255, 496, 201],
[ 2, 0, 1, 27, 0],
[1438, 3785, 3589, 4174, 2215],
[1342, 4043, 4009, 4665, 3033]
])

In [2]:
print(ridership[1:3, 3:5])

[[2328 2539]
 [6461 2691]]


In [3]:
ridership[3].mean()

3235.6

In [4]:
ridership[3, :].mean()

3235.6

In [5]:
np.arange(3)[:, np.newaxis] +np.arange(6)

array([[0, 1, 2, 3, 4, 5],
       [1, 2, 3, 4, 5, 6],
       [2, 3, 4, 5, 6, 7]])

In [13]:
n=np.array([[9, 2, 4, 2],
   [4, 3, 6, 1],
   [6, 6, 8, 8],
   [2, 9, 8, 8]])

In [14]:
np.sum(n>7) 

6

In [15]:
n[n>7]

array([9, 8, 8, 9, 8, 8])